// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMmaOpbYzjV3W3aMgdkr1fzqa8BwgPaSI',
    appId: '1:194467807514:web:1b5002e5037261356f2ca3',
    messagingSenderId: '194467807514',
    projectId: 'kishal-stylish',
    authDomain: 'kishal-stylish.firebaseapp.com',
    storageBucket: 'kishal-stylish.firebasestorage.app',
    measurementId: 'G-YYV53TRG5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK3dbkLCqM-EgUlgg5W2374j2RmRLWVAM',
    appId: '1:194467807514:android:94089e02b4d461606f2ca3',
    messagingSenderId: '194467807514',
    projectId: 'kishal-stylish',
    storageBucket: 'kishal-stylish.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoDfBd-iz6Zyjc5F5SRSAvqL2TlmtXhEA',
    appId: '1:194467807514:ios:d81fcd555ce0cdd56f2ca3',
    messagingSenderId: '194467807514',
    projectId: 'kishal-stylish',
    storageBucket: 'kishal-stylish.firebasestorage.app',
    iosBundleId: 'com.example.stylish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoDfBd-iz6Zyjc5F5SRSAvqL2TlmtXhEA',
    appId: '1:194467807514:ios:d81fcd555ce0cdd56f2ca3',
    messagingSenderId: '194467807514',
    projectId: 'kishal-stylish',
    storageBucket: 'kishal-stylish.firebasestorage.app',
    iosBundleId: 'com.example.stylish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMmaOpbYzjV3W3aMgdkr1fzqa8BwgPaSI',
    appId: '1:194467807514:web:951ee431ea961a846f2ca3',
    messagingSenderId: '194467807514',
    projectId: 'kishal-stylish',
    authDomain: 'kishal-stylish.firebaseapp.com',
    storageBucket: 'kishal-stylish.firebasestorage.app',
    measurementId: 'G-TJ4KWQCZKV',
  );
}
